// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvw3X8JIkhHQfz_1RQ5IUp8Si2Xrzuymc',
    appId: '1:437097852625:android:be5267f61f7c3c7b37dff0',
    messagingSenderId: '437097852625',
    projectId: 'nagpurmart-86ea5',
    storageBucket: 'nagpurmart-86ea5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJE6rVYSsw7jE6ASdJvbtBtidjJ8atUs0',
    appId: '1:437097852625:ios:ecdc81a906b4754337dff0',
    messagingSenderId: '437097852625',
    projectId: 'nagpurmart-86ea5',
    storageBucket: 'nagpurmart-86ea5.firebasestorage.app',
    androidClientId: '437097852625-4oq3o8rr61udaf9aubrnjlc3ef237cra.apps.googleusercontent.com',
    iosClientId: '437097852625-frpdn2na106o7eokute2uccijb3ir900.apps.googleusercontent.com',
    iosBundleId: 'com.nagpurmart.rider',
  );
}
